### ISSUE TITLE
Unable to add Duka One S6W to Home Assistant

### ISSUE THREAD

**Issue by Jydepotte** [dingusdk/ha-dukaone#19]
Hi,

I am unable to add my Duka One S6 Plus Wifi to Home Assistant using this integration. Are there any hacks to get it to recognize my unit?

![image](https://github.com/dingusdk/ha-dukaone/assets/145715005/8f64d459-0063-4243-9125-c9662be64a0e)

Kind regards

Jan Lebeck

**Comment by dingusdk** [comment]
Are you sure the IP is correct? Duka One uses network broadcasts, and you can also specify the broadcast address as ip:192.168.1.255
Because it is broadcast it may also be your network or how you host HA that cause it. F.x I know running HA in docker on windows  can cause problems. I run in in docker on linux and this work ok. Running natively on linux should also work.
Do you have any errors in the HA log related to the duka one integration?

**Comment by Jydepotte** [comment]
Yes the IP is correct - but the password was not. I did not notice that the password for the device only allows up to 8 characters. It works as expected now. Thank you.
